name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: luismedel/setup-bluish@374ea72522537aa56008cd40559836b4a3d3d19b
      - name: Check installation
        run: |
          bluish --version
