name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.11'

      - uses: luismedel/setup-bluish@9b84ab4415890a2e3bb1d1438197ba2ea46e58f8
        id: bluish

      - name: Check installation
        run: |
          echo "Installed Bluish version: ${{ steps.bluish.outputs.bluish-version }}"
